#!/bin/bash

# AI Tutor Instructions Setup Script
# ====================================
# This script sets up the AI tutor system in your project

set -e  # Exit on error

echo "🎓 AI Tutor Instructions Setup"
echo "=============================="
echo ""

# Detect project root (current directory)
PROJECT_ROOT="$(pwd)"
echo "📁 Project root: $PROJECT_ROOT"

# Create .ai directory if it doesn't exist
if [ ! -d "$PROJECT_ROOT/.ai" ]; then
    echo "📂 Creating .ai directory..."
    mkdir -p "$PROJECT_ROOT/.ai"
fi

# Download or copy tutor instructions
TUTOR_INSTRUCTIONS_URL="https://raw.githubusercontent.com/YOUR_USERNAME/tutor-instructions/main/tutor-instructions.md"

echo "📥 Installing tutor instructions..."

# Try to download if URL is accessible, otherwise copy from local
if command -v curl &> /dev/null; then
    if [ -f "$(dirname "$0")/tutor-instructions.md" ]; then
        # Running from cloned repo
        cp "$(dirname "$0")/tutor-instructions.md" "$PROJECT_ROOT/.ai/tutor-instructions.md"
    else
        # Download from GitHub
        curl -fsSL "$TUTOR_INSTRUCTIONS_URL" -o "$PROJECT_ROOT/.ai/tutor-instructions.md"
    fi
elif command -v wget &> /dev/null; then
    if [ -f "$(dirname "$0")/tutor-instructions.md" ]; then
        cp "$(dirname "$0")/tutor-instructions.md" "$PROJECT_ROOT/.ai/tutor-instructions.md"
    else
        wget -q "$TUTOR_INSTRUCTIONS_URL" -O "$PROJECT_ROOT/.ai/tutor-instructions.md"
    fi
else
    echo "❌ Error: Neither curl nor wget is available. Please install one of them."
    exit 1
fi

echo "✅ Tutor instructions installed to .ai/tutor-instructions.md"

# Setup GitHub Copilot instructions
COPILOT_DIR="$PROJECT_ROOT/.github"
COPILOT_FILE="$COPILOT_DIR/copilot-instructions.md"

echo ""
echo "⚙️  Setting up GitHub Copilot integration..."

# Create .github directory if needed
if [ ! -d "$COPILOT_DIR" ]; then
    mkdir -p "$COPILOT_DIR"
fi

# Add tutor instructions to copilot-instructions.md
if [ -f "$COPILOT_FILE" ]; then
    # Check if already integrated
    if grep -q "SENIOR TUTOR AGENT INSTRUCTIONS" "$COPILOT_FILE"; then
        echo "ℹ️  Tutor instructions already in copilot-instructions.md"
    else
        echo "" >> "$COPILOT_FILE"
        echo "# AI Tutor Mode" >> "$COPILOT_FILE"
        echo "Include instructions from .ai/tutor-instructions.md" >> "$COPILOT_FILE"
        echo "" >> "$COPILOT_FILE"
        cat "$PROJECT_ROOT/.ai/tutor-instructions.md" >> "$COPILOT_FILE"
        echo "✅ Tutor instructions added to existing copilot-instructions.md"
    fi
else
    # Create new file
    cat "$PROJECT_ROOT/.ai/tutor-instructions.md" > "$COPILOT_FILE"
    echo "✅ Created .github/copilot-instructions.md"
fi

# Create .gitignore entries if needed
GITIGNORE="$PROJECT_ROOT/.gitignore"
echo ""
echo "📝 Updating .gitignore..."

if [ -f "$GITIGNORE" ]; then
    if ! grep -q ".ai/tutor-progress.md" "$GITIGNORE"; then
        echo "" >> "$GITIGNORE"
        echo "# AI Tutor Progress (personal)" >> "$GITIGNORE"
        echo ".ai/tutor-progress.md" >> "$GITIGNORE"
        echo "✅ Added .ai/tutor-progress.md to .gitignore"
    else
        echo "ℹ️  .gitignore already configured"
    fi
else
    echo "# AI Tutor Progress (personal)" > "$GITIGNORE"
    echo ".ai/tutor-progress.md" >> "$GITIGNORE"
    echo "✅ Created .gitignore"
fi

# Create placeholder files (will be auto-generated by agent)
echo ""
echo "📋 Setting up tracker files..."

if [ ! -f "$PROJECT_ROOT/.ai/tutor-syllabus.md" ]; then
    cat > "$PROJECT_ROOT/.ai/tutor-syllabus.md" << 'EOF'
# Tutor Syllabus

## Authoritative Sources
Primary: (To be defined based on tech stack)
Secondary: Official Documentation

## Topics
(Will be auto-generated on first interaction with AI tutor)

To customize:
1. Add your preferred books/resources under "Authoritative Sources"
2. Define topic order and depth
3. The AI tutor will follow this syllabus strictly
EOF
    echo "✅ Created placeholder tutor-syllabus.md"
else
    echo "ℹ️  tutor-syllabus.md already exists"
fi

# Success message
echo ""
echo "======================================"
echo "✨ AI Tutor Setup Complete! ✨"
echo "======================================"
echo ""
echo "📁 Files created:"
echo "   - .ai/tutor-instructions.md"
echo "   - .ai/tutor-syllabus.md (placeholder)"
echo "   - .github/copilot-instructions.md"
echo ""
echo "🎯 Next steps:"
echo "   1. Edit .ai/tutor-syllabus.md to customize your learning path"
echo "   2. Start working with GitHub Copilot - it will now act as your tutor"
echo "   3. Progress will be tracked in .ai/tutor-progress.md (auto-created)"
echo ""
echo "💡 Tip: Ask your AI assistant to 'build a feature' and watch it teach first!"
echo ""
